[build]
builder = "NIXPACKS"
watchPatterns = ["ticktracker/frontend/**"]

[deploy]
startCommand = "sh -c 'export PATH=$PATH:./node_modules/.bin && next start -p $PORT -H 0.0.0.0'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
