[build]
builder = "NIXPACKS"
watchPatterns = ["ticktracker/frontend/**"]

[deploy]
startCommand = "sh -c 'npm start -- -p $PORT -H 0.0.0.0'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
